### ISSUE TITLE
Missing runtime dependency javax.servlet-api?

### ISSUE THREAD

**Issue by dajester2013** [geronimo-iia/winstone#29]
I could not get my war to run from the commandline until I manually placed the javax.servlet-api-3.1.0.jar into my lib directory - class not found javax/servlet/ServletContext.

I downloaded the latest version of winstone-jsp from maven central.

Stack trace:

```
Thu, 27 Aug 2015 05:09:58 717 GMT, BootStrap Info: Main-Class=net.winstone.Winst
one
INFO  27/08/15 00:09:58.818 [main]: stage 1/3: Loading arguments...
INFO  27/08/15 00:09:58.819 [main]: stage 2/3: Loading WebApplication configurat
ion...
INFO  27/08/15 00:09:58.819 [main]: stage 3/3: compute JSP classpath...
Thu, 27 Aug 2015 05:09:58 828 GMT, BootStrap Warning: Exception occur : null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.intelligentsia.keystone.boot.BootStrap.invokeMain(BootStrap.java:
383)
        at org.intelligentsia.keystone.boot.BootStrap.main(BootStrap.java:242)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletContext
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.winstone.core.ObjectPool.<init>(ObjectPool.java:103)
        at net.winstone.Server.initialize(Server.java:118)
        at net.winstone.Server.start(Server.java:106)
        at net.winstone.Winstone.main(Winstone.java:25)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContext
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 21 more
Thu, 27 Aug 2015 05:09:58 885 GMT, BootStrap Info: Exit
```

**Comment by geronimo-iia** [comment]
Actually, winstone is on servlet 2.5.
